server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: ${APP_NAME:api-selsolun}

  datasource:
    url: jdbc:mysql://${DB_HOST:192.168.1.101}:${DB_PORT:3306}/${DB_NAME:crypto_app}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root_password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:none}
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

application:
  security:
    allowed-origins: ${ALLOWED_ORIGINS:http://localhost:4200}